"""Add password column to users table

Revision ID: 5796008fb388
Revises: cc1cbbdd08f0
Create Date: 2024-11-09 00:17:16.319587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5796008fb388'
down_revision = 'cc1cbbdd08f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))
        batch_op.drop_column('passwordhash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwordhash', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
